feat: when manager creates student, he can create his/her fees too
hei-school/hei-admin-ui pull request #147
Opened 2023-02-21 13:20 UTC by NyAndoMayah

2023-02-22 14:01 UTC, heiherilala requested changes

2023-02-22 14:01 UTC, heiherilala commented on src/__tests__/Manager.Fee.cy.js
> +    cy.intercept('GET', `/students/${student1Mock.id}/fees?page=1&page_size=500`, addFeeMock(feesMock, createFeeWithPredefinedDataMock(feeDateToSearch)))
Don't get by value because that value can change. get by order of li

2023-02-22 14:01 UTC, heiherilala commented on src/__tests__/Manager.cy.js
> +    //cy.wait('@getManager1')
Son't make it as comment, delet it directly

2023-02-22 14:01 UTC, heiherilala commented on src/__tests__/Manager.Fee.cy.js
> +    cy.get('.show-page > .MuiToolbar-root > .MuiTypography-root').click()
Maybe make some comment when it's difficult  to see what the code do, like this

2023-02-22 14:01 UTC, heiherilala commented on src/__tests__/Manager.Fee.cy.js
> +    cy.get('.show-page > .MuiToolbar-root > .MuiTypography-root').click()
```suggestion
    cy.get('.show-page > .MuiToolbar-root > .MuiTypography-root').click()//click in ...
```

2023-02-22 14:01 UTC, heiherilala commented on src/__tests__/Manager.cy.js
> +    cy.intercept('GET', '/students?page=1&page_size=10', [createdStudent, ...studentsMock]).as('getStudents')
Delete last item of "studentsMock" for maiking their number to 10

2023-02-22 14:01 UTC, heiherilala commented on src/__tests__/Manager.cy.js
> +    cy.get('[data-value="jan22"]').click()
Don't get by value because that value can change. get by order of li

2023-02-22 14:01 UTC, heiherilala commented on src/__tests__/Manager.cy.js
> +    cy.get('[data-value="jan22"]').click()
Don't get by value because that value can change. get by order of li

2023-02-22 14:01 UTC, heiherilala commented on src/__tests__/Manager.cy.js
> +    const createdFeesWithStudent = createFeeWithManualDataMock(feeDateToSearch, monthlyAmount, comment, monthsNumber)
make initialization of variables in top

2023-02-22 14:01 UTC, heiherilala commented on src/__tests__/mocks/responses/student-api.ts
> +}
I don't understand the difference between both of them

2023-02-22 14:01 UTC, heiherilala commented on src/conf.js
>  }
don't forget to delete it if you will not use it after modification

2023-02-22 14:01 UTC, heiherilala commented on src/operations/fees/FeesCreate.js
> +  const defaultIsPredefinedFirstDueDate = true
There is a repetition of "defaultIsPredefinedType" and "defaultIsPredefinedFirstDueDate", put it (and the others if it exists) in an object outside the function so that all other functions can access it. (for no repetition)

2023-02-22 14:01 UTC, heiherilala commented on src/operations/fees/FeesCreate.js
> +        let end = start + feesConf[j].monthsNumber
use "const" if start and end is not supposed to change

2023-02-22 14:01 UTC, heiherilala commented on src/providers/studentProvider.ts
> +    fees.length !== 0 && (await payingApi().createStudentFees(studentResponse?.id!, fees))
start the function just when "createOrUpdateStudents" is finished, but not in the same line

2023-02-23 10:54 UTC, JrManjato approved these changes

2023-02-23 10:56 UTC, heiherilala approved these changes

2023-02-23 10:59 UTC, merged