feat: generate scholarship certificate
hei-school/hei-admin-ui pull request #440
Opened 2024-01-13 14:23 UTC by RickaPrincy

2024-01-13 16:21 UTC, YumeT023 requested changes

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/GenCertificateButton.js
> +  const FILE_NAME = "Certificat_Scolarité.pdf";
get constants out of the component

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/GenCertificateButton.js
> +        document.body.appendChild(link);
/!\ AVOID MUTATING THE DOM DIRECTLY, use React ref instead

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/GenCertificateButton.js
> +  const generate = useCallback(() => {
only memoize performant critical function.
here `generate` fn fetches data from the api and appends an anchor to the body which doesn't evolve any expensive compution at all 

/!\ `generate` is not explicit at all and doesn't actually generate anything,
It fetches something from the api instead, `get...` would be more appropriate

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/GenCertificateButton.js
> +    notify("Certificat de scolarité en cours de téléchargement", {
notify fn should be part of the [deps,]

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/GenCertificateButton.js
> +export function GenCertificateButton({studentId}) {
`GenCertificateButton` is proper to student and is too dependent to student to be a utility cmp.
move it inside `students` module under `components` instead

the same goes for `SelectSpecialization`

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/students/index.js
> +  edit: <ProfileEdit isOwnProfile={false} isStudent={true} />,
_STYLE_

...`={true}` can be omitted

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/SelectSpecialization.js
> +export function SelectSpecialization({ignoreRole = false, ...props}) {
conditionally render `SelectSpecialization` instead of passing `ignoreRole`
add some comments when using rest parameters `...props` as the component doesn't tell exactly what `props` would be, you could pass it through `selectFieldProps` maybe ...

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/SelectSpecialization.js
> +export function getSpecializationValue(specialization) {
is `getSpecializationValue` used anywhere else ?

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/SelectSpecialization.js
> +  const SpecializationList = Object.entries(SpecializationField).map((el) => ({
/!\ case is incorrect
map the `SpecializationField` to a constant and out of this component instead as it is not dependent to the cmp

el[0] el[1] is semantically incorrect

name them in the (anonym) fn of `map` using object destructuring

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/SelectSpecialization.js
> +  return ignoreRole || isStudent ? (
render `SelectInput` directly, conditionally render the `cmp` instead

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/GenCertificateButton.js
> +          new Blob([response.data], {type: "application/pdf"})
correctly check if response is not null and that data (size/len/byteLen is not 0)
to avoid any potential `NPE` or any other Runtime err

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/GenCertificateButton.js
> +        notify("Échec de téléchargement. Veuillez réessayer", {
notify is always called with
```js
{autoHideDuration: 5000}
```
option

/!\ avoid repetition
instead, create a hook wrapper (another hook that wraps the notify() that only take the msg arg)

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/GenCertificateButton.js
> +      <Download />
alias `Download` cmp to be more explicit
`DownloadIcon` is better

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/profile/ProfileShow.js
> +const renderSpecialization = ({specialization_field}) =>
`renderSpecialization` should take directly the `specialization_field` in param instead of the `record` itself

the same goes for most of the `renderers`
/!\ put a TODO on 'em

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/profile/ProfileShow.js
> +  const isStudent = role === WhoamiRoleEnum.STUDENT;
/!\ avoid repetition
extract these role checks to a custom react hook
as It is everywhere in the project
put a refactor TODO for now

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/profile/ProfileShow.js
> +export const ProfileLayout = ({isStudent = false}) => {
either don't export `ProfileLayout` or move it in `components` subdir
If used accross operations, move it in operations/common/components

/!\ put a refactor TODO

2024-01-13 16:21 UTC, YumeT023 commented on src/operations/utils/GenCertificateButton.js
> +import {studenstFileApi} from "../../providers/api";
Remove unused imports

2024-01-13 16:49 UTC, RickaPrincy commented on src/operations/utils/SelectSpecialization.js
> +export function getSpecializationValue(specialization) {
yes ... used in profilShow

2024-01-14 18:50 UTC, YumeT023 requested changes

2024-01-14 18:50 UTC, YumeT023 commented on src/hooks/useNotifyMessage.js
> +export const useNotifyMessage = (config = {}) => {
instead, alias the `useNotify` of react-admin as `_useNotify` or `useNotifyInternal`
then rename `useNotifyMessage` into `useNotify` as usual (rename the file too)

2024-01-14 18:50 UTC, YumeT023 commented on src/hooks/useRole.js
> +    ...auth,
`useRole` shouldn't expose any other thing apart from the `role`

you could return the `is...` and the `role` itself but not the `auth`

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/profile/ProfileEdit.js
> +        {(isStudent || role.isStudent) && (
what does this mean ? `isStudent` then role.isStudent ? ... arrange this a bit

2024-01-14 18:50 UTC, YumeT023 commented on src/hooks/useRole.js
> +  return {
react will evaluate the 
```js
auth.role === _
```
directly, ... instead, turn isStudent, isManager, isTeacher into (anonymous) fn

2024-01-14 18:50 UTC, YumeT023 commented on src/hooks/useRole.js
> +export function useRole() {
/!\ move  `useRole` hooks to 
security/hooks/useRole as it's part of the `core` and related to security/permission

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/profile/ProfileEdit.js
> +          <SelectSpecialization disabled={isOwnProfile} />
`ProfileEdit` ... is it still necessary to check if it is my own profile or not ?
You shouldn't even get to `ProfileEdit` unless its your own profile
/!\ re-adjust this or add some comments to explain it

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/profile/ProfileEdit.js
> +          disabled={isOwnProfile}
... ProfileEdit should only be accessed by its owner, would have been okay if the cmp was `ProfileShow`

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/profile/ProfileEdit.js
> +const ProfileEdit = ({isOwnProfile, isStudent}) => {
... `isOwnProfile` in `ProfileEdit` doesn't make any sense

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/profile/ProfileShow.js
> +  const {isStudent, id} = useRole();
/!\  `useRole` must _ONLY_ check and expose current user `role`

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/StudentCreate.js
> +        <SelectSpecialization ignoreRole={true} />
what is `ignoreRole` prop for ?

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/StudentShow.js
> +      <ProfileLayout isStudent={true} />
/!\ use implicit truthy bool prop
`<Cmp isStudent />`

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/StudentShow.js
> +            to={`/students/${record.id}/fees`}
rename `record` => `student`

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/StudentShow.js
>        actions={role === WhoamiRoleEnum.MANAGER && <ActionsOnShow />}
use the `useRole` hook

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/components/GenCertificateButton.js
> +          throw new Error("The response data from the server is null");
response.data may be defined but is 0 byte.

improve the checks.
- data is truthy
- data `size/byteLength/length` (rtfd which prop is associated the file object from server `ArrayBuffer`)
   - should be `> 0` 

those things may lead to unexpected  behaviour if not checked properly

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/components/GenCertificateButton.js
> +        certificateLink.current.href = window.URL.createObjectURL(
`current` prop of `certificateLink` is accessed multiple times,
instead, put it in a variable `certificateLink`, suffix react ref with `ref`, `certificateLinkRef` here

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/components/GenCertificateButton.js
> +          throw new Error("The response data from the server is null");
Do not throw an err when the data is not gud, instead report it with a `toast` notif or smth
as network conn is not as reliable as u'd expect...

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/components/GenCertificateButton.js
> +      .catch(() =>
always add braces when you're not returning anything from the anonymous_fn

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/components/GenCertificateButton.js
> +    <>
but it inside a kind of container, `div` or something, ...

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/components/SelectSpecialization.js
> +export function getSpecializationValue(specialization) {
instead, make a _STATIC_ constant object for mapping
then `SPECIALIZATIONS[key] ?? "Tronc commun"`

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/components/SelectSpecialization.js
> +export function getSpecializationValue(specialization) {
why is this `fn` exported outside of `SelectSpecialization` scope ?

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/components/index.js
> +export * from "./GenCertificateButton";
rename this `cmp`, as it is not really a button, simply `GetCertificate` (also, it is not about generating anything)

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/students/index.js
> +  edit: <ProfileEdit isOwnProfile={false} isStudent />,
You may check role inside of `<ProfileEdit /> directly

what is `isOwnProfile` for ?

2024-01-14 18:50 UTC, YumeT023 commented on src/operations/profile/ProfileShow.js
> +                  render={(record) =>
/!\ put a TODO to rename these `record` => the associated data like (`student`, `fee`, ...etc)

2024-01-14 18:50 UTC, YumeT023 commented on src/hooks/index.js
> +export * from "./useRole";
useRole hook is part of the `core`, not related to toggle or notification hook, move it in security/hooks instead

/!\ put TODO to move the `useCreateFees` and `useStudentRef` too

2024-01-15 08:29 UTC, RickaPrincy commented on src/operations/students/components/SelectSpecialization.js
> +export function getSpecializationValue(specialization) {
Use to show the value of specialization on profileShow

2024-01-15 08:38 UTC, RickaPrincy commented on src/operations/students/index.js
> +  edit: <ProfileEdit isOwnProfile={false} isStudent />,
`isStudent` is used to say that the profile we wanna edit is a student's profile  (we need it 'cause Manager can edit student's profile, teacher's profile...) 
Samething for  isOwnProfile ...

2024-01-15 08:39 UTC, RickaPrincy commented on src/operations/profile/ProfileShow.js
> +                  render={(record) =>
But ProfilShow is for all resources ... we cannot determine if it's student or fee ....

2024-01-15 10:21 UTC, RickaPrincy commented on src/operations/profile/ProfileEdit.js
> +const ProfileEdit = ({isOwnProfile, isStudent}) => {
like .... I can edit your profile ...

2024-01-15 15:06 UTC, YumeT023 commented on src/operations/profile/ProfileShow.js
> +                  render={(record) =>
I mean, Profile means `user` ... not fee in any case
and here, the fact is that you are explicitly rendering the ffield if the user is a student so record must be a student and not fee ...

2024-01-15 15:09 UTC, YumeT023 commented on src/operations/students/components/SelectSpecialization.js
> +export function getSpecializationValue(specialization) {
why isn't it named like the other ? 
why isn't it named `renderSpec...` ?

2024-01-15 15:11 UTC, YumeT023 commented on src/operations/students/index.js
> +  edit: <ProfileEdit isOwnProfile={false} isStudent />,
Instead make another variant of ProfileEdit for Teacher and Student instead of having lots of flag here and there

2024-01-15 18:11 UTC, RickaPrincy commented on src/operations/profile/ProfileShow.js
> +                  render={(record) =>
ahh ... ok ok

2024-01-15 18:11 UTC, RickaPrincy commented on src/operations/profile/ProfileShow.js
> +                  render={(record) =>
user seems logic ...

2024-01-15 18:14 UTC, RickaPrincy commented on src/operations/students/index.js
> +  edit: <ProfileEdit isOwnProfile={false} isStudent />,
Why not TODO ? the PR will be very huge for that 
Like I put that one another PR ...

2024-01-15 18:16 UTC, RickaPrincy commented on src/operations/students/components/SelectSpecialization.js
> +export function getSpecializationValue(specialization) {
getSpecializationValue is no longer present as said on the other change request, now it's a simple `const` as you said

2024-01-16 08:41 UTC, YumeT023 requested changes

2024-01-16 08:41 UTC, YumeT023 commented on src/__tests__/GetCertificate.cy.js
> +  specTitle("Student and Manager Can get a certificate for students"),
More concise description: Student certificate

2024-01-16 08:41 UTC, YumeT023 commented on src/__tests__/GetCertificate.cy.js
> +  specTitle("Student and Manager Can get a certificate for students"),
test both `student` and `manager` case as you said in the spec_title

2024-01-16 08:41 UTC, YumeT023 commented on src/__tests__/GetCertificate.cy.js
> +    it("can edit students", () => {
Edit student ?

2024-01-16 08:41 UTC, YumeT023 commented on src/__tests__/GetCertificate.cy.js
> +        .and("include", "blob");
construct a blob from the href uri and test that its size is > 0
also test when the retrieved file is null (the server responded null) or when the returned file is == 0

2024-01-16 08:41 UTC, YumeT023 commented on src/operations/profile/ProfileEdit.js
> +        {(isStudent || role.isStudent()) && (
what is isStudent || role.isStudent() ? ... get rid of such ambiguity

2024-01-16 08:41 UTC, YumeT023 commented on src/operations/profile/ProfileShow.js
> +              {(isStudent || role.isStudent()) && (
ambiguous

2024-01-16 08:41 UTC, YumeT023 commented on src/operations/profile/ProfileShow.js
> +          {isStudent() && <GetCertificate studentId={id} />}
the `role` context is needed here
`role.isStudent()` is more explicit and helps avoid any ambiguity such as:
- The shown profile is a student
- The user who views the profile is a student

2024-01-16 08:41 UTC, YumeT023 commented on src/operations/students/StudentShow.js
> +  const {isManager} = useRole();
always include the _role_ ctx , role.isManager()

2024-01-16 08:41 UTC, YumeT023 commented on src/operations/students/components/SelectSpecialization.js
> +  const specializationChoices = Object.entries(SPECIALIZATION_VALUE).map(
again, specializationChoices can be computed outside of this component

2024-01-16 08:41 UTC, YumeT023 commented on src/operations/students/index.js
> +  edit: <ProfileEdit isOwnProfile={false} isStudent />,
put a TODO
/!\ Create ProfileEdit variant: TeacherProfileEdit, StudentProfileEdit instead of having a flag that says if the ProfileEdit component should show the student version ...

2024-01-16 08:49 UTC, YumeT023 commented
test commit is scoped under test
e.g: test: get certificate

2024-01-16 12:48 UTC, RickaPrincy commented on src/operations/profile/ProfileEdit.js
> +        {(isStudent || role.isStudent()) && (
I think I'll put some comments then... anyway, isStudent is passed through the cmp to say that the record is a student ( when manager want to watch a profile os student, or teachers)
role.isStudent() is to check if the current logged user is a student...

2024-01-16 12:52 UTC, RickaPrincy commented on src/__tests__/GetCertificate.cy.js
> +    it("can edit students", () => {
my bad ... copy paste error

2024-01-16 16:30 UTC, YumeT023 requested changes

2024-01-16 16:30 UTC, YumeT023 commented on src/__tests__/GetCertificate.cy.js
> +import {mount, unmount} from "@cypress/react";
LGTM!

Separate interaction from assertion (separate click, thing... from contains, and eq)

2024-01-16 16:30 UTC, YumeT023 commented on src/operations/profile/ProfileEdit.js
> +          (isStudent || role.isStudent()) && (
Remove the useless comment
put this in a variable before render

2024-01-16 16:30 UTC, YumeT023 commented on src/operations/profile/ProfileShow.js
> +                (isStudent || role.isStudent()) && (
Remove the useless comment
put the condition in a well-named variable

2024-01-16 17:30 UTC, YumeT023 requested changes

2024-01-16 17:30 UTC, YumeT023 commented on src/operations/profile/ProfileEdit.js
> +  const isRecordOfStudent = isStudent || role.isStudent();
not clear enough

2024-01-16 17:30 UTC, YumeT023 commented on src/operations/profile/ProfileShow.js
> +              {isRecordOfStudent && (
not clear enough

2024-01-16 17:52 UTC, YumeT023 approved these changes

2024-01-17 11:17 UTC, merged