feat: use feesTemplates to create fees
hei-school/hei-admin-ui pull request #453
Opened 2024-01-29 14:20 UTC by RickaPrincy

2024-01-29 20:06 UTC, YumeT023 requested changes

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
> +    cy.get("#predefinedType").click();
use data-testid instead of id for testing

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
>      cy.get('[data-testid="menu-list-action"]').click();
TODO: create custom cypress command to "getByTestid"

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
> +    cy.get("@getFeesTemplates");
cy.wait

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
> +      const requestBody = intersection.request.body;
rename this to `toCreate`

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
> +      const feesToCreate = requestBody[0];
`fee`

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/utils.js
> +  const lastDayOfMonth = new Date(year, month + 1, 1);
unnecessary variable, inline return!

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/utils.js
> +export const getEndOfMonth = (year, month) => {
move this somewhere else

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/utils.js
> +export const testFeesWithTemplate = (feesToCreate, template) => {
find more appropriate name, be more PRECISE
If the name is not sufficient, add some comments

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/utils.js
> +export const testFeesWithTemplate = (feesToCreate, template) => {
fee or fees ?

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/FeeCreate.js
> +    fetchRef();
why don't you do this inside useStudentRef ?

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/components/FeeFields.js
> +  const validateMonthsNumber = [
directly put these validations constraints to the element props

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/components/SelectDueDatetime.js
> +function getCurrentDate() {
Ban this!
avoid unnecessary abstraction

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/components/SelectDueDatetime.js
> +  return new Intl.DateTimeFormat("fr-FR", {month: "long"}).format(
put the `DateTimeFormat` instance to a constant
This impl recreate it each loop

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/components/SelectDueDatetime.js
> +  const currentDate = getCurrentDate();
ban the getCurrentDate() fn

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/components/SelectDueDatetime.js
> +  const validateYear = [required(), number(), minValue(2021)];
direclty put this validation constraint in the element prop

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/components/SelectPredefinedType.js
> +    setValue("amount", feeConfig.amount);
see React hook form
`reset`

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/components/FeeFields.js
> +import {FEESTEMPLATES_CHOICES} from "../utils/feesTemplatesChoices.js";
SHOULD not be part of utils

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/components/FeeFields.js
> +          onChange={udpateFeeConfig}
fix typo

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/components/SelectPredefinedType.js
> +      choices={data || []}
add default value instead
{ data = [] } = useGet...

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +function createComment(comment, i, number_of_payments) {
bad API
rename params name

bad naming
use camelCase

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +function getEndOfMonth(predefinedYear, predefinedMonth, index) {
bad API
why are these params prefixed by predefined ?
un-clear comment

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +  const tempDate = new Date(currentDate);
new Date(..., ..., ...)
you can inline it

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +      : getNextDate(firstDueDatetime, i);
use comment like this for magic variable

```js
doSomething(i /* tell what i is here */);
```

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +      creation_datetime: new Date().toISOString(),
for more precise datetime
create new Date() before everything

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +  const feesToCreate = [];
rename to fees

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/feesTemplates/FeesTemplateCreate.js
> +  const validateAmount = [required(), number(), minValue(1)];
direclty put this validation constrait in the element prop

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/feesTemplates/FeesTemplateCreate.js
> +  const id = useMemo(() => uuidv4(), []);
avoid unnecessary optimization

id won't be used unless you are confirming the fee creation, so create it in transform

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/feesTemplates/FeesTemplatesEdit.js
> +  const validateAmount = [required(), number(), minValue(1)];
directly put in prop

2024-01-29 20:06 UTC, YumeT023 commented on src/operations/feesTemplates/FeesTemplateCreate.js
> +import {useMemo} from "react";
order your imports

2024-01-29 20:06 UTC, YumeT023 commented on src/ui/haLayout/menu/utils/HaMenu.js
> +          <img src="/menu-logo.png" style={{width: 40, height: 27}} />
import this img instead

2024-01-29 20:06 UTC, YumeT023 commented on src/App.js
>  import {HaLayout} from "./ui/haLayout";
order imports in this file

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
>        .and("contain", statusRenderer(interceptedFeeMock.status))
no, directly put the literal value here instead of using any additional fn

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
>      cy.get('[aria-label="fees"]').click();
TODO: cy.getByTestid

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
> +    cy.get("#predefinedYear").clear().type(FIRST_YEAR);
use data-testid for testing

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
> +    cy.get("#number_of_payments").click().type(NUMBER_OF_PAYMENTS);
use data-testid everywhere

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
>      cy.contains("Enregistrer").click();
Write functional test

intercept the sent request on save then check that it has sent the correct payload

2024-01-29 20:06 UTC, YumeT023 commented on src/__tests__/Manager.Student.cy.js
>      fillInputs();
fill what inputs ?
rename this fn

2024-01-31 03:05 UTC, YumeT023 requested changes

2024-01-31 03:05 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
> +import {prettyPrintMoney, statusRenderer} from "../operations/utils";
group imports

2024-01-31 03:05 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
> +import {getEndOfMonth} from "../operations/utils";
group them by subdir

2024-01-31 03:05 UTC, YumeT023 commented on src/__tests__/utils.js
> +export const verifyFeesWithTemplate = (feeToCreate, template) => {
assertFeeMatchesTemplate

2024-01-31 03:05 UTC, YumeT023 commented on src/hooks/useStudentRef.js
> +  }, [studentRef, studentId]);
missing setStudentRef dep
also causes infinite re-renders as studentRef is part of the dep while you are setting its value on line 15

Add the correct deps

2024-01-31 03:05 UTC, YumeT023 commented on src/hooks/useStudentRef.js
> +    fetchRef();
void fetchRef();

to intentionally ignore Promise\<T\> return

2024-01-31 03:05 UTC, YumeT023 commented on src/hooks/useStudentRef.js
> +      const student = await dataProvider.getOne("students", {id: studentId});
uncaught error

handle them

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/FeeCreate.js
> +      transform={(feesRecord) => createFeesApi(feesRecord, studentId)}
are you creating multiple fees ? if not then simply rename to fee (omit Record as since its not really important here)

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/FeeEdit.js
> +import {useState} from "react";
order imports

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/FeeList.js
>    const role = authProvider.getCachedRole();
TODO: update to use  `useRole` hook

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/components/SelectDueDatetime.js
> +const MONTHS_LISTS = Array.from({length: 12}, (_, month) => {
space

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/components/SelectDueDatetime.js
> +  const validateYear = [required(), number(), minValue(2021)];
directly put inside prop

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/components/SelectPredefinedType.js
> +    reset(
are these all the field prop keys ?
if so, then simply reset to feeConfig

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/components/SelectPredefinedType.js
> +  const {data = [], isLoading} = useGetList("fees-templates");
bind data to `feeTemplates` var
```js
{ data: feeTemplates = [], ...
```

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/components/SelectPredefinedType.js
> +      {...props}
TODO: all previously declared props could be overwritten by redeclaring them through `props`

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/utils/commonStyle.js
> +export const rowStyle = (record, _index) => {
/!\ TO function name

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/utils/commonStyle.js
> +export const FEE_SELECT_STYLE = {
FEE_SIZES

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +  const dateAfterIndex = new Date(year, month + index + 1, 0);
inline return

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +  return numberOfPayemnts === 9
what is 9 
always add explicit comment for magic numbe/variable/...

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +function createComment(baseComment, monthValue, numberOfPayemnts) {
monthIndex

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +function getEndOfMonth(year, month, index) {
rename this file to feeFactory and do not reexport it in index.js since you will add all functions that create fee-related objects

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/feesTemplates/FeesTemplateCreate.js
> +  const id = uuidv4();
alias v4 as uuid()

no,  at line 22


```js
transform={(feeTemplate) => ({...feeTemplate, id: uuid() })}
```

this way, you're not creating any uuid unless you're really creating a fee template

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/feesTemplates/FeesTemplateCreate.js
> +      redirect={() => `fees-templates`}
unnecessary template literal

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/feesTemplates/FeesTemplatesList.js
> +        render={(feestype) => prettyPrintMoney(feestype.amount)}
feeType not fee**s**type

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/students/StudentCreate.js
> +import {useState} from "react";
order imports

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/students/StudentCreate.js
>    const [canCreateFees, setCanCreateFees] = useState(false);
use toggle

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/students/utils/createStudentApi.js
> +import {createFeesApi} from "../../fees/utils";
move to studentMapper or studentFactory

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/students/utils/createStudentApi.js
> +  let fees = [];
__CONST__

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +function getEndOfMonth(year, month, index) {
what differenciate this function from https://github.com/hei-school/hei-admin-ui/pull/453/files#diff-01fc2e35c584b1e97aa92cec664f6632e1ec6651ba0984a725b544bbf41790eb

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +    const currentIsoDate = new Date().toISOString();
create this date earlier instead of recreating it every loop

rename to currentDate (unnecessary ISO ctx)

2024-01-31 03:05 UTC, YumeT023 commented on src/operations/fees/utils/createFeesApi.js
> +      comment: createComment(comment, i, number_of_payments),
always add explicit comment for magic var like "i" here

2024-01-31 03:05 UTC, YumeT023 commented on src/ui/haLayout/menu/utils/HaMenu.js
> +  const logout = () => {
async

await the authProvider.logout() as its a async fn before reloading the page

2024-01-31 03:45 UTC, RickaPrincy commented on src/operations/fees/FeeCreate.js
> +      transform={(feesRecord) => createFeesApi(feesRecord, studentId)}
it's multiple fees ... using feesTemplate

2024-01-31 04:06 UTC, RickaPrincy commented on src/operations/fees/components/SelectPredefinedType.js
> +    reset(
No, there is another field

2024-01-31 04:30 UTC, RickaPrincy commented on src/operations/fees/utils/createFeesApi.js
> +function getEndOfMonth(year, month, index) {
The another one is to getEndOfMonth of the give year and month, the another one is to get it also but using index (only for fees)
But yeah, I can combine then

2024-01-31 12:03 UTC, closed without merging