refactor: folder structure
hei-school/hei-admin-ui pull request #492
Opened 2024-03-02 12:42 UTC by RickaPrincy

2024-03-02 13:38 UTC, YumeT023 requested changes

2024-03-02 13:38 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
> +
why?
remove

2024-03-02 13:38 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
> +import {prettyPrintMoney, statusRenderer} from "../operations/utils";
renderer is not a function name

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/comments/CommentList.js
> +import {formatDate} from "../../utils";
why is formatDate imported from ./utils  and not ./utils/date ?

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/common/utils/frenchSupport.js
> +import {EnableStatus, Sex} from "@haapi/typescript-client";
file => typo_util / enum_util

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/common/utils/index.js
> +export {userStatusInFr} from "./userStatusInFr";
use of userStatusInFr results in NPE, check your exports

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/fees/ByStatusFeeList.js
> +
unnecessary br

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/fees/ByStatusFeeList.js
> +import {rowStyle} from "./utils";
either from style or constant but not utils

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/fees/FeeEdit.js
> +import {statusRenderer} from "../utils";
not a function name

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/fees/FeeShow.js
>  const dateTimeRenderer = (data) => {
not a function name

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/fees/FeeShow.js
>  const dateTimeRenderer = (data) => {
is it used anywhere ?

2024-03-02 13:38 UTC, YumeT023 commented on src/utils/date.js
> +export const DATE_OPTIONS = {
are DATE_OPTIONS / TIME_OPTIONS used independently anywhere ?
no ? simply merge the declaration in DATETIME_OPTIONS

is DATETIME_OPTIONS used anywhere else ? 
no ? do not export it, just provide a way to format a date that uses it internally

2024-03-02 13:38 UTC, YumeT023 commented on src/utils/date.js
> +export const getEndOfMonth = (year, month) => {
why + 1, comment

2024-03-02 13:38 UTC, YumeT023 commented on src/utils/getObjValue.js
> +/**
.js => .ts

2024-03-02 13:38 UTC, YumeT023 commented on src/utils/index.js
> +export {NOOP_FN} from "./noop";
do not batch import everywhere

let the module be scoped as usual

2024-03-02 13:38 UTC, YumeT023 commented on src/utils/userRoleInFr.js
> +export function getUserRoleInFr(userRole) {
not supposed to be in src/utils

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/fees/FeeList.js
> +import {commentFunctionRenderer, prettyPrintMoney} from "../utils";
not fn name

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/common/utils/frenchSupport.js
> +export const EMPTY_TEXT = "Non défini.e";
EMPTY_TEXT => UNDEFINED

used too often so ... move to src/utils and import everytime

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/common/components/fields/BirthDateField.js
> +  ...typographyProps
sx is destructured ... why ?

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/comments/CommentList.js
> +import {getUserRoleInFr} from "../../utils";
use scoped module

2024-03-02 13:38 UTC, YumeT023 commented on src/operations/comments/CommentList.js
>  const LIST_PER_PAGE = 10;
=> ITEMS_PER_PAGE

2024-03-02 13:58 UTC, RickaPrincy commented on src/operations/fees/FeeShow.js
>  const dateTimeRenderer = (data) => {
dateTimeRenderer no

2024-03-02 14:00 UTC, RickaPrincy commented on src/utils/date.js
> +export const DATE_OPTIONS = {
Yes, used on DateField from react admin which require directly an DATE_OPTIONS

2024-03-02 14:05 UTC, RickaPrincy commented on src/utils/date.js
> +export const getEndOfMonth = (year, month) => {
Get the 0th day of the next month, which results in the end of the current month.

2024-03-02 17:37 UTC, YumeT023 requested changes

2024-03-02 17:37 UTC, YumeT023 commented on src/operations/common/components/ProfileLayout.js
> +  const [isOpen, , toggle] = useToggle();
better having the '_set' here to tell that the middle value is a fn that sets the isOpen, but not used

2024-03-02 17:37 UTC, YumeT023 commented on src/operations/groups/GroupList.js
> +import { useRole } from "../../security/hooks";
format your code!

2024-03-02 17:37 UTC, YumeT023 commented on src/operations/groups/GroupList.js
> +      actions={<GroupFilters isManager={role.isManager()} />}
does this props need to be passed as props ?

2024-03-02 17:37 UTC, YumeT023 commented on src/operations/groups/GroupStudentList.js
> +  const [isOpen, , toggle] = useToggle();
_set to tell whats on the skipped var

2024-03-02 17:37 UTC, YumeT023 commented on src/ui/haToolbar/importButton/ImportButton.js
> +  const [isShown, , toggleMenu] = useToggle();
rename these, 
what is open ? shown ?

2024-03-02 17:37 UTC, YumeT023 commented on src/operations/common/utils/money.ts
> +const CURRENCY: string = "Ar";
unnecessary typings

2024-03-02 17:37 UTC, YumeT023 commented on src/operations/common/utils/money.ts
> +export const renderPrettyMoney = (amount: number): string => {
render money is enough!

2024-03-02 17:37 UTC, YumeT023 commented on src/operations/common/utils/typo_util.js
> +import { UNDEFINED } from "../../../utils/undefined";
kinda ambiguous to javascript 'undefined', replace to NOT_DEFINED instead

2024-03-02 17:37 UTC, YumeT023 commented on src/utils/getObjValue.ts
> +type Obj = { [key: string]: any };
unnecessary typings

2024-03-02 17:37 UTC, YumeT023 commented on src/utils/getObjValue.ts
> +export function getObjValue(obj: Obj, path: string): any {
use Record<string, any> (object literal) instead

2024-03-02 17:37 UTC, YumeT023 commented on src/utils/getObjValue.ts
> +      { ...obj }
why'd you want to create a clone of the obj ?

2024-03-02 17:37 UTC, YumeT023 commented on src/utils/undefined.js
> +export const UNDEFINED = "Non défini.e";
undefined.js => constants.ts

2024-03-02 17:37 UTC, YumeT023 commented on src/utils/index.js
>  export {getObjValue} from "./getObjValue";
export * from "./.........

2024-03-02 17:37 UTC, YumeT023 commented on src/utils/getObjValue.ts
> +export function getObjValue(obj: Obj, path: string): any {
'any' is not a good return type here, consider using 'unknown' (type needs to be checked prior to its usage)

2024-03-02 17:37 UTC, YumeT023 commented on src/__tests__/Manager.Fee.cy.js
> +import {statusRenderer} from "../operations/utils";
... fix

2024-03-02 17:37 UTC, YumeT023 commented on src/__tests__/Manager.Payment.cy.js
>  import App from "../App";
TODO: use of core fn should be minimized in test assertions, explicit declaration is best
e.g: instead of importing the 'renderPrettyMoney' fn, directly write the rendered money as is

2024-03-02 17:37 UTC, YumeT023 commented on src/operations/comments/CommentList.js
>  import defaultProfilePicture from "../../assets/blank-profile-photo.png";
default & non_lib imports should be at below every imports

2024-03-02 17:37 UTC, YumeT023 commented on src/operations/fees/FeeShow.js
>            record.status === "LATE"
refactor

2024-03-02 17:37 UTC, YumeT023 commented on src/ui/haLayout/appBar/UserInfo.js
> +        .finally(()=>setIsLoading(false));
format your code

what happens here if an error occur then ?

if the return value of the callback is not meant to be used, dont inline it

2024-03-04 06:05 UTC, RickaPrincy commented on src/operations/groups/GroupStudentList.js
> +  const [isOpen, , toggle] = useToggle();
cause a warning...

2024-03-04 10:10 UTC, RickaPrincy commented on src/operations/common/components/ProfileLayout.js
> +  const [isOpen, , toggle] = useToggle();
cause a warning

2024-03-05 13:07 UTC, RickaPrincy commented on src/utils/getObjValue.ts
> +      { ...obj }
Not to change the value of the original object

2024-03-05 13:07 UTC, RickaPrincy commented on src/utils/getObjValue.ts
> +      { ...obj }
Cause I reduce the object

2024-03-17 15:14 UTC, closed without merging