Feat/create monitor role
hei-school/hei-admin-ui pull request #709
Opened 2024-09-16 09:54 UTC by Rakotonirinaonjaniaina

2024-09-17 05:58 UTC, NyAndoMayah requested changes

2024-09-17 05:58 UTC, NyAndoMayah commented on src/App.jsx
> +import MonitorStudentList from "./operations/monitorStudent/MonitorStudentList";
refactor your imports : 
- the default import should be on the bottom
- { AnnouncementList } -> {AnnouncementList}
- ./operations/ -> @/operations
- Use index.js in operations/monitorStudents because there are so many imported elements from this folder

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/common/components/ProfileLayout.jsx
> +import { DocList } from "@/operations/docs/components/DocList";
Refactor the imports

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/common/components/ProfileLayout.jsx
> +          <Box
remove the unecessary spaces

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/fees/FeeList.jsx
> +import MonitorStudentList from "../monitorStudent/MonitorStudentList";
Refactor the imports

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/fees/FeeList.jsx
> +      {isMonitor() && (
isMonitor() || isManager() &&

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/monitorStudent/MonitorStudentCreate.jsx
> +const MonitorStudentCreate = () => (
I think there is already a StudentCreate somewhere ?

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/monitorStudent/MonitorStudentDocs.jsx
> +import {Link, useParams} from 'react-router-dom';
Put this under import React from 'react';

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/monitorStudent/MonitorStudentList.jsx
> +        <>
Use Mui Box instead of react fragment

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/monitorStudent/MonitorStudentShow.jsx
> +import {Box} from "@mui/material";
refactor the imports

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/monitorStudent/index.jsx
> +  Show: MonitorStudentShow,
show instead of Show

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/monitorStudent/index.jsx
> +const monitorStudent = {
Use this in the App.ts

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/monitors/MonitorCreate.jsx
> +const transformMonitor = (record) => {
redundant functions, can you generalize this as transformUser and put it in utils or something like that ?

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/monitors/MonitorList.jsx
> +        <>
Use Box instead

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/monitors/MonitorList.jsx
> +          <ExportButton
Redundant

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/monitors/MonitorShow.jsx
> +
refactor the imports

2024-09-17 05:58 UTC, NyAndoMayah commented on src/operations/monitors/index.jsx
> +const monitors = {
use this in App then

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/dataProvider.ts
> +  if (resourceType === "monitorStudents") return monitorStudentProvider;
monitor-students

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/dataProvider.ts
> +      resourceType === "students" ||
Question : is this necessary ? Why did you put this ?

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/monitorProvider.ts
> +    try {
use await

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/monitorProvider.ts
> +      throw new Error(
Do not throw an error

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/monitorProvider.ts
> +      console.log(result.data);
remove console.log

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/monitorProvider.ts
> +      console.error(`Failed to fetch monitor with id=${id}:`, error);
Do not throw an error

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/monitorProvider.ts
> +        const result = await usersApi().updateMonitorById(monitor.id, monitor);
const {data}

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/monitorStudentProvider.ts
> +    try {
use await

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/monitorStudentProvider.ts
> +        page || 1,
there is already a default page and perPage so..no need

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/monitorStudentProvider.ts
> +      throw error;
Do not throw error

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/monitorStudentProvider.ts
> +        1,
No magic numbers pls

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/monitorStudentProvider.ts
> +      return result.data.find((student) => student.id === id);
No, it's the role of the backend, you have to ask them to give you a getOne endpoint

2024-09-17 05:58 UTC, NyAndoMayah commented on src/providers/profileProvider.ts
>  import {WhoamiRoleEnum} from "@haapi/typescript-client";
This should be on top

2024-09-17 05:58 UTC, NyAndoMayah commented on src/security/permissions.ts
> +
remove unnecessary line

2024-09-17 05:58 UTC, NyAndoMayah commented on src/ui/haLayout/menu/MonitorMenu.jsx
> +  Group as GroupIcon,
refactor imports

2024-09-17 05:59 UTC, NyAndoMayah commented
@Rakotonirinaonjaniaina  Rebase the preprod because there are some important changes, and resolve the conflicts.

2024-09-25 11:26 UTC, JeanMarc-RAJAONARIVELONA commented on src/operations/fees/FeeList.jsx
> +        <MonitorFeeList studentId={studentId} studentRef={studentRef} />
redundance

2024-10-02 19:59 UTC, closed without merging