feat: exam
hei-school/hei-admin-ui pull request #775
Opened 2024-11-18 09:15 UTC by Michellah

2024-11-21 07:28 UTC, NyAndoMayah requested changes

2024-11-21 07:28 UTC, NyAndoMayah commented on src/operations/exams/ExamCreate.tsx
> +import authProvider from "@/providers/authProvider";
order your imports

2024-11-21 07:28 UTC, NyAndoMayah commented on src/operations/exams/ExamCreate.tsx
> +  const userRole = user.role;
object destructuration

2024-11-21 07:28 UTC, NyAndoMayah commented on src/operations/exams/ExamCreate.tsx
> +          <>
avoid using React Fragment, use Mui Box instead

2024-11-21 07:28 UTC, NyAndoMayah commented on src/operations/exams/ExamCreate.tsx
> +            )}{" "}
why did you put `{" "}`

2024-11-21 07:28 UTC, NyAndoMayah commented on src/operations/exams/ExamCreate.tsx
> +          fullWidth
order your attributes

2024-11-21 07:28 UTC, NyAndoMayah commented on src/operations/exams/ExamCreate.tsx
> +  const {data: awardedCourses = []} = useGetList("awarded-courses", {
can you explain me this

2024-11-21 07:28 UTC, NyAndoMayah commented on src/operations/exams/ExamCreate.tsx
> +  const courseChoice = useMemo(() => {
typo

2024-11-21 07:28 UTC, NyAndoMayah commented on src/operations/exams/ExamCreate.tsx
> +        {userRole == "MANAGER" ? (
isManager in useRole

2024-11-21 07:28 UTC, NyAndoMayah commented on src/operations/exams/ExamList.tsx
> +  const {data: exams = []} = useListContext();
go in line

2024-11-21 07:28 UTC, NyAndoMayah commented on src/operations/exams/components/SelectField.tsx
> +    <FormControl fullWidth variant="outlined" sx={{flex: 1}}>
order your attributes

2024-11-21 07:28 UTC, NyAndoMayah commented on src/providers/examProvider.tsx
> +    } = filter;
handle error here because what if one those attributes does not exist

2024-11-26 19:00 UTC, Michellah commented on src/operations/exams/ExamCreate.tsx
> +  const {data: awardedCourses = []} = useGetList("awarded-courses", {
it is to have the course associated with a teacher after he has selected the teacher

2024-12-03 06:25 UTC, merged