chore: convert all numerical dates into literal dates
hei-school/hei-admin-ui pull request #85
Opened 2022-10-20 12:48 UTC by NyAndoMayah

2022-10-24 16:37 UTC, hei-teacher requested changes

2022-10-24 16:37 UTC, hei-teacher commented on src/operations/fees/ByStatusFeeList.js
> +        <DateField source='creation_datetime' label='Date de création' locales='fr-FR' options={{ year: 'numeric', month: 'long', day: 'numeric' }} />
It's too repetitive with L24, refactor: create a custom DateField component that defines by default locales and options.

2022-10-27 11:25 UTC, fmaurica requested changes

2022-10-27 11:25 UTC, fmaurica commented on src/operations/profile/ProfileShow.js
> +      <DateField source='entrance_datetime' label="Date d'entrée chez HEI" locales='fr-FR' options={{ year: 'numeric', month: 'long', day: 'numeric' }} />
Redundant props everywhere ==> refactor

2022-10-27 12:22 UTC, fmaurica approved these changes

2022-10-27 12:22 UTC, merged